"""
AI Package Hallucination & Supply Chain Firewall.

Protects against:
1. Hallucinated / phantom package dependencies generated by LLMs.
2. Slopsquatting & dependency confusion attacks where malicious actors register
   hallucinated package names on PyPI.
"""

import ast
import json
import urllib.request
import urllib.error
import sys
from typing import Dict, List, Set, Any, Optional

# Standard Python libraries that should not be queried against PyPI
STDLIB_MODULES: Set[str] = {
    "abc", "argparse", "array", "ast", "asyncio", "base64", "binascii", "bisect",
    "builtins", "calendar", "cmath", "collections", "concurrent", "configparser",
    "contextlib", "copy", "csv", "ctypes", "dataclasses", "datetime", "decimal",
    "difflib", "dis", "doctest", "email", "enum", "errno", "faulthandler", "filecmp",
    "fnmatch", "fractions", "functools", "gc", "getopt", "getpass", "glob", "gzip",
    "hashlib", "heapq", "hmac", "html", "http", "idlelib", "imaplib", "imghdr",
    "importlib", "inspect", "io", "ipaddress", "itertools", "json", "keyword",
    "linecache", "locale", "logging", "lzma", "math", "mimetypes", "mmap",
    "modulefinder", "msilib", "msvcrt", "multiprocessing", "netrc", "nntplib",
    "numbers", "operator", "optparse", "os", "pathlib", "pdb", "pickle",
    "pickletools", "pkgutil", "platform", "plistlib", "poplib", "posix", "posixpath",
    "pprint", "profile", "pstats", "pty", "pwd", "py_compile", "pyclbr", "pydoc",
    "queue", "quopri", "random", "re", "readline", "reprlib", "resource", "rlcompleter",
    "runpy", "sched", "secrets", "select", "selectors", "shelve", "shlex", "shutil",
    "signal", "site", "smtpd", "smtplib", "sndhdr", "socket", "socketserver",
    "spwd", "sqlite3", "ssl", "stat", "statistics", "string", "stringprep",
    "struct", "subprocess", "sunau", "symbol", "symtable", "sys", "sysconfig",
    "syslog", "tabnanny", "tarfile", "telnetlib", "tempfile", "termios", "test",
    "textwrap", "threading", "time", "timeit", "tkinter", "token", "tokenize",
    "tomllib", "trace", "traceback", "tracemalloc", "tty", "turtle", "turtledemo",
    "types", "typing", "unicodedata", "unittest", "urllib", "uu", "uuid", "venv",
    "warnings", "wave", "weakref", "webbrowser", "winreg", "winsound", "wsgiref",
    "xdrlib", "xml", "xmlrpc", "zipapp", "zipfile", "zipimport", "zlib", "zoneinfo"
}

# Pre-cached popular verified packages to guarantee instant response and avoid network rate limits
KNOWN_VERIFIED_PACKAGES: Dict[str, Dict[str, Any]] = {
    "fastapi": {"version": "0.115.0", "summary": "FastAPI framework, high performance, easy to learn"},
    "uvicorn": {"version": "0.32.0", "summary": "The lightning-fast ASGI server"},
    "pydantic": {"version": "2.9.2", "summary": "Data validation using Python type annotations"},
    "pytest": {"version": "8.3.3", "summary": "pytest: simple powerful testing with Python"},
    "qdrant-client": {"version": "1.12.0", "summary": "Qdrant - vector database client for Python"},
    "sentence-transformers": {"version": "3.1.1", "summary": "Multilingual Sentence & Image Embeddings"},
    "requests": {"version": "2.32.3", "summary": "Python HTTP for Humans"},
    "httpx": {"version": "0.27.2", "summary": "A next-generation HTTP client for Python"},
    "numpy": {"version": "2.1.2", "summary": "Fundamental package for scientific computing with Python"},
    "pandas": {"version": "2.2.3", "summary": "Powerful data structures for data analysis"},
    "cryptography": {"version": "43.0.1", "summary": "cryptography is a package designed to expose cryptographic primitives"},
    "flask": {"version": "3.0.3", "summary": "A simple framework for building complex web applications"},
    "django": {"version": "5.1.2", "summary": "A high-level Python web framework"},
    "jinja2": {"version": "3.1.4", "summary": "A very fast and expressive template engine"},
    "python-dotenv": {"version": "1.0.1", "summary": "Read key-value pairs from a .env file"},
    "torch": {"version": "2.5.0", "summary": "Tensors and Dynamic neural networks in Python"},
}

_PACKAGE_CACHE: Dict[str, Optional[Dict[str, Any]]] = dict(KNOWN_VERIFIED_PACKAGES)


def extract_imported_packages(python_code: str) -> List[str]:
    """Parse Python code using AST and extract top-level imported package names."""
    try:
        tree = ast.parse(python_code)
    except SyntaxError:
        return []

    imported: Set[str] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root_pkg = alias.name.split(".")[0].strip()
                if root_pkg:
                    imported.add(root_pkg)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                root_pkg = node.module.split(".")[0].strip()
                if root_pkg:
                    imported.add(root_pkg)

    return sorted(list(imported))


def query_pypi_package(package_name: str, timeout: float = 3.0) -> Optional[Dict[str, Any]]:
    """
    Check if a package exists on the official PyPI registry via its public JSON API.
    Returns package metadata if found, or None if the package does not exist (404).
    """
    pkg_key = package_name.lower().replace("_", "-")
    if pkg_key in _PACKAGE_CACHE:
        return _PACKAGE_CACHE[pkg_key]

    url = f"https://pypi.org/pypi/{pkg_key}/json"
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Kavach-SupplyChain-Firewall/1.0"}
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            info = data.get("info", {})
            meta = {
                "version": info.get("version", "unknown"),
                "summary": info.get("summary", ""),
                "license": info.get("license", "unknown"),
                "home_page": info.get("home_page", ""),
            }
            _PACKAGE_CACHE[pkg_key] = meta
            return meta
    except urllib.error.HTTPError as e:
        if e.code == 404:
            _PACKAGE_CACHE[pkg_key] = None
            return None
        # In case of 5xx or transient errors, return stub with warning
        return {"version": "unverified", "summary": f"PyPI check returned HTTP {e.code}"}
    except Exception:
        # Network timeout or offline mode
        return None


def verify_code_dependencies(
    python_code: str,
    project_internal_modules: Optional[Set[str]] = None,
    allow_network_query: bool = True
) -> Dict[str, Any]:
    """
    Audit code dependencies against PyPI to flag hallucinated or non-existent packages.
    """
    if project_internal_modules is None:
        project_internal_modules = {"app", "backend", "frontend", "tests", "tools", "data", "conftest"}

    all_imports = extract_imported_packages(python_code)
    third_party: List[str] = []
    
    for pkg in all_imports:
        clean_name = pkg.lower().replace("_", "-")
        if pkg in STDLIB_MODULES or clean_name in STDLIB_MODULES:
            continue
        if pkg in project_internal_modules or clean_name in project_internal_modules:
            continue
        third_party.append(pkg)

    hallucinated: List[str] = []
    verified: List[Dict[str, Any]] = []
    warnings: List[str] = []

    for pkg in third_party:
        clean_name = pkg.lower().replace("_", "-")
        # Check cache or known list first
        if clean_name in KNOWN_VERIFIED_PACKAGES:
            verified.append({
                "package": pkg,
                "version": KNOWN_VERIFIED_PACKAGES[clean_name]["version"],
                "summary": KNOWN_VERIFIED_PACKAGES[clean_name]["summary"],
                "status": "VERIFIED_OFFICIAL"
            })
            continue

        if not allow_network_query:
            warnings.append(f"Network verification skipped for '{pkg}' (offline mode)")
            continue

        meta = query_pypi_package(clean_name)
        if meta is None:
            hallucinated.append(pkg)
        else:
            verified.append({
                "package": pkg,
                "version": meta.get("version", "unknown"),
                "summary": meta.get("summary", ""),
                "status": "VERIFIED_PYPI"
            })

    is_safe = len(hallucinated) == 0

    return {
        "is_safe": is_safe,
        "total_imports": len(all_imports),
        "all_imports": all_imports,
        "third_party_imports": third_party,
        "hallucinated_packages": hallucinated,
        "verified_packages": verified,
        "warnings": warnings,
        "risk_verdict": "SAFE" if is_safe else "SUPPLY_CHAIN_RISK_DETECTED",
        "message": (
            "All dependencies verified against PyPI registry."
            if is_safe
            else f"Blocked {len(hallucinated)} hallucinated package(s) not found on PyPI: {', '.join(hallucinated)}"
        )
    }
